### ISSUE TITLE
Nový vzhled Mozilla.cz

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#27]
Toto je přehled toho, co je potřeba udělat pro nový vzhled Mozilla.cz, přibližně i v tomto pořadí. Určitě jako první budou všechny úpravy možné přímo ve frontierline-theme a až pak nějaká child šablona, ideálně co nejmenší.

# frontierline-theme
- [x] utm_source podle domény webu (https://github.com/craigcook/frontierline-theme/pull/11)
- [ ] menu v záhlaví (https://github.com/craigcook/frontierline-theme/pull/13)
- [ ] v záhlaví tlačítko explore firefox / download firefox / nic (https://github.com/craigcook/frontierline-theme/pull/13)
- [x] ~~logo v záhlaví a jeho odkaz (https://github.com/craigcook/frontierline-theme/pull/13)~~
- [ ] on/off newsletter subscribe (https://github.com/craigcook/frontierline-theme/pull/15)
- [ ] vlastní obsah zápatí (https://github.com/craigcook/frontierline-theme/pull/18)
- [x] widget pro sociální tlačítka (https://github.com/craigcook/frontierline-theme/pull/18)
- [x] odlišit "menu" s widgety ikonkou od hlavního responsivního menu (https://github.com/craigcook/frontierline-theme/pull/20)
- [x] česká lokalizace (https://github.com/craigcook/frontierline-theme/pull/21)
- [x] *stabilní generování náhledů (https://github.com/craigcook/frontierline-theme/pull/14)
- [x] *favicon, apple-touch a msapplication ikony (to umí přímo WordPress + https://github.com/craigcook/frontierline-theme/pull/16)
- [ ] *og:image při sdílení (https://github.com/craigcook/frontierline-theme/pull/17)
- [ ] *konfigurovatelné umístění tlačítek pro sdílení a rubrik (`.entry-tools`) nad a/nebo pod článkem/stránkou (https://github.com/craigcook/frontierline-theme/issues/26)
- [x] *barva tlačítka ke stažení (https://github.com/craigcook/frontierline-theme/pull/30)
- [x] *výška záhlaví s obrázkem (https://github.com/craigcook/frontierline-theme/pull/33)
- [ ] *vlastní styl přihlašovací stránky s použitím loga ze záhlaví (https://github.com/craigcook/frontierline-theme/issues/41)

# frontierline-theme ? child
- [x] ~~*skrýt informace o verzích z URL adres~~

# child
- [x] parent css přes enqueue skript místo css include (https://github.com/MozillaCZ/frontierline-mozillacz/issues/1)
- [x] font awesome
- [x] 404 (https://github.com/MozillaCZ/frontierline-mozillacz/issues/5)
- [x] pořádný obrázek v záhlaví (https://github.com/MozillaCZ/frontierline-mozillacz/issues/2)

# styly pro obsah
- [x] `<a hreflang="...">` (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] spany `.nabidka`, `.soubor` a `.codear` (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] /stahnout/ (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] /stahnout/... (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] další z #26 (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] `.news-logo` (https://github.com/MozillaCZ/frontierline-mozillacz/issues/4)
- [x] ~widgety~
- [x] ~`.fa.image-like`~

# obrázky (nastavit při nasazení)
- [x] logo se světlým textem do zápatí
- [x] náhledové obrázky pro posledních N zpráviček

 `*` stačí dodatečně

**Comment by jrychly** [comment]
Nevím, jestli je tohle správné vlákno, ale jak chceme řešit [prezentace.mozilla.cz](https://prezentace.mozilla.cz/), jelikož tam je taky stará šablona a pokud vím, tak to běží oddělené.

**Comment by MikkCZ** [comment]
@jrychly https://github.com/MozillaCZ/prezentace/issues/4

**Comment by MikkCZ** [comment]
Vzhled je nasazený, během víkendu doladím už jenom pár detailů.
